apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: monitoring
  labels:
    release: prometheus-grafana
spec:
  namespaceSelector:
    matchNames:
      - plug-namespace
  selector:
    matchLabels:
      plug: backend-pods
  endpoints:
    - port: http
      path: /metrics
      interval: 30s