apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: plug-namespace
  labels:
    release: prometheus-grafana
spec:
  selector:
    matchLabels:
      plug: backend-pods
  endpoints:
    - port: http
      path: /metrics
      interval: 30s