---
- name: Find volumes without connection
  amazon.aws.ec2_vol_info:
    region: "{{ aws_region }}"
    filters:
      status: available
  register: ebs_volumes

- name: Filter volumes older than {{ cleanup_days }} days
  shell: |
    create_epoch=$(date -d "{{ item.create_time }}" +%s)
    current_epoch=$(date +%s)
    echo $(( (current_epoch - create_epoch) / 86400 ))
  register: volume_age
  loop: "{{ ebs_volumes.volumes }}"

- name: Delete old volumes
  amazon.aws.ec2_vol:
    region: "{{ aws_region }}"
    id: "{{ item.item.id }}"
    state: absent
  loop: "{{ volume_age.results }}"
  when: item.stdout | int >= cleanup_days