# Generated by Django 5.0.7 on 2024-07-22 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DrugParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isHighOrLowSatisfaction', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('drug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drug')),
            ],
        ),
        migrations.CreateModel(
            name='DrugOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('grams_in_stock', models.IntegerField()),
                ('price_per_gram', models.FloatField()),
                ('chosen_offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chosenoffer')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='drug_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drugoffer'),
        ),
        migrations.AddField(
            model_name='drug',
            name='drug_parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drugparameter'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('isAcceptedByPlug', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('chosen_offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chosenoffer')),
                ('rating', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='api.rating')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPartner', models.BooleanField()),
                ('isSlanderer', models.BooleanField()),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Plug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('drug_offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drugoffer')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50)),
                ('hashed_password', models.CharField(max_length=100)),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to='api.client')),
                ('plug', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to='api.plug')),
            ],
        ),
    ]
