# Generated by Django 5.0.7 on 2024-08-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugoffer',
            name='currency',
            field=models.CharField(),
        ),
    ]
