# Generated by Django 5.0.7 on 2024-08-06 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='drug_offer',
        ),
        migrations.RemoveField(
            model_name='drugoffer',
            name='chosen_offer',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='chosen_offer',
        ),
        migrations.RemoveField(
            model_name='plug',
            name='drug_offer',
        ),
        migrations.RemoveField(
            model_name='plug',
            name='location',
        ),
        migrations.AddField(
            model_name='chosenoffer',
            name='drug_offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.drugoffer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chosenoffer',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.meeting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugoffer',
            name='drug',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.drug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='plug',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.plug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='isHighOrLowClientSatisfaction',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='isHighOrLowPlugSatisfaction',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chosenoffer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
