# Generated by Django 5.0.7 on 2025-01-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_drugoffer_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plug',
            name='isPartner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plug',
            name='isSlanderer',
            field=models.BooleanField(default=False),
        ),
    ]
