# Generated by Django 5.0.7 on 2024-08-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_meeting_rating_remove_appuser_meeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='isPartner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='isSlanderer',
            field=models.BooleanField(default=False),
        ),
    ]
