# Generated by Django 5.0.7 on 2024-08-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_appuser_ispartner_alter_appuser_isslanderer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='isHighOrLowClientSatisfaction',
            field=models.CharField(blank=True, default=None, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='isHighOrLowPlugSatisfaction',
            field=models.CharField(blank=True, default=None, max_length=4),
            preserve_default=False,
        ),
    ]
