# Generated by Django 5.0.7 on 2024-08-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_meeting_isacceptedbyplug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='isHighOrLowClientSatisfaction',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='isHighOrLowPlugSatisfaction',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
