# Generated by Django 5.0.7 on 2024-08-06 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_meeting_ishighorlowclientsatisfaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='plug',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_user', to='api.plug'),
        ),
    ]
