# Generated by Django 5.0.7 on 2024-08-06 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_drug_description_drugoffer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugoffer',
            name='plug',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='api.plug'),
            preserve_default=False,
        ),
    ]
