# Generated by Django 5.0.7 on 2024-08-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_drugoffer_plug'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='street_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='street_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
