# Generated by Django 5.0.7 on 2024-08-08 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_location_city_alter_location_street_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='plug',
        ),
        migrations.AddField(
            model_name='plug',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plug', to=settings.AUTH_USER_MODEL),
        ),
    ]
