# Generated by Django 5.0.7 on 2024-08-08 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_appuser_plug_plug_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plug',
            name='user',
        ),
        migrations.AddField(
            model_name='appuser',
            name='plug',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_user', to='api.plug'),
        ),
    ]
