---
plugin: amazon.aws.aws_ec2

aws_profile: default

regions:
  - "eu-north-1"

filters:
  "tag:Environment": "dev"
  "instance-state-name": running

keyed_groups:
  - key: tags.Environment
    prefix: "env"

compose:
  ansible_host: public_ip_address