apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: plug-namespace
  labels:
    plug: backend-secret
type: Opaque
data:
  DB_NAME: cG9zdGdyZXM=
  DB_USER: YWRtaW4=
  DB_PASSWORD: YWRtaW4=
  EMAIL_HOST_USER: dGhlLnBsdWcub3JnYW5pemF0aW9uQGdtYWlsLmNvbQ==
  EMAIL_HOST_PASSWORD: amhtYyB2ZnJlIGhhdGwgZm5qbQ==
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLTIxaDcoczgzeiNpbjUmKGJuNTF2eGw3d3plODVqJDM1aSVsOCF3cSZvNjE2LStpaWk1