apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: plug-namespace
  labels:
    plug: backend-secret
type: Opaque
data:
  DB_NAME: ${POSTGRES_DB}
  DB_USER: ${POSTGRES_USER}
  DB_PASSWORD: ${POSTGRES_PASSWORD}
  EMAIL_HOST_USER: ${EMAIL_HOST_USER}
  EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
  SECRET_KEY: ${SECRET_KEY}