apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: plug-namespace
  labels:
    plug: db-secret
type: Opaque
data:
  POSTGRES_DB: ${DB_NAME}
  POSTGRES_USER: ${DB_USER}
  POSTGRES_PASSWORD: ${DB_PASSWORD}