apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: plug-namespace
  labels:
    plug: pgadmin-secret
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}