---
- name: Configure NFS Server
  hosts: nfs
  become: yes
  tasks:
    - name: Install NFS server packages
      apt:
        name:
          - nfs-kernel-server
        state: present
        update_cache: yes

    - name: Create NFS share directory
      file:
        path: /mnt/nfs_share
        state: directory
        owner: nobody
        group: nogroup
        mode: '0777'

    - name: Export NFS share
      lineinfile:
        path: /etc/exports
        line: "/mnt/nfs_share *(rw,sync,no_subtree_check)"
        create: yes

    - name: Restart NFS server
      service:
        name: nfs-kernel-server
        state: restarted