apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
  labels:
    plug: backend-secret
type: Opaque
stringData:
  DB_NAME: {{ .Values.backendSecret.dbName }}
  DB_USER: {{ .Values.backendSecret.dbUser }}
  DB_PASSWORD: {{ .Values.backendSecret.dbPassword }}
  EMAIL_HOST_USER: {{ .Values.backendSecret.emailHostUser }}
  EMAIL_HOST_PASSWORD: {{ .Values.backendSecret.emailHostPassword }}
  SECRET_KEY: {{ .Values.backendSecret.secretKey }}