apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    plug: backend-pods
  ports:
  - protocol: TCP
    port: {{ .Values.backendService.port }}
    targetPort: 8080
  type: {{ .Values.backendService.type }}