apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db-storage-class
  namespace: {{ .Values.namespace }}
provisioner: cluster.local/nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: {{ .Values.dbStorageClass.archiveOnDelete | quote }}