apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    plug: db-pods
  ports:
  - protocol: TCP
    port: {{ .Values.dbService.port }}
    targetPort: 5432
  type: {{ .Values.dbService.type }}