apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.namespace }}
  labels:
    plug: db-secret
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.dbSecret.postgresDb }}
  POSTGRES_USER: {{ .Values.dbSecret.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.dbSecret.postgresPassword }}