apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    plug: frontend-pods
  ports:
  - protocol: TCP
    port: {{ .Values.frontendService.port }}
    targetPort: 8080
  type: {{ .Values.frontendService.type }}