apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: {{ .Values.namespace }}
  labels:
    plug: pgadmin-secret
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgadminSecret.pgadminDefaultEmail }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.pgadminSecret.pgadminDefaultPassword }}