Vagrant.configure("2") do |config|
    servers=[
        {
          :hostname => "NFS",
          :box => "bento/ubuntu-22.04",
          :ip => "192.168.56.1",
          :ssh_port => '2222'
        }
    ]

    servers.each do |machine|
        config.vm.define machine[:hostname] do |server|
            server.vm.box = machine[:box]
            server.vm.hostname = machine[:hostname]
            server.vm.network :private_network, ip: machine[:ip]
            server.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
            server.vm.synced_folder '.', '/vagrant', disabled: true
            server.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", 3072]
                vb.customize ["modifyvm", :id, "--cpus", 2]
            end
        end
    end
end