apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db-storage-class
  namespace: plug-namespace
provisioner: cluster.local/nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: "false"