serviceMonitor:
  selfMonitor:
    enabled: true
    labels:
      release: prometheus-grafana

  enabled: true
  defaults:
    labels:
      release: prometheus-grafana

  targets:
    - name: backend
      url: http://backend-service.plug-namespace.svc.cluster.local:8080/api/herb/list/
    - name: frontend
      url: http://frontend-service.plug-namespace.svc.cluster.local