apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: plug-namespace
  labels:
    plug: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      plug: frontend-pods
  template:
    metadata:
      labels:
        plug: frontend-pods
    spec:
      containers:
      - name: frontend-container
        image: wallys02/the-plug-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1