apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-backend-network-policy
  namespace: plug-namespace
spec:
  podSelector:
    matchLabels:
      plug: backend-pods
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          plug: frontend-pods
    ports:
    - protocol: TCP
      port: 8080