apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
  namespace: plug-namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: <userAssignedIdentityID>
    keyvaultName: "the-plug"
    tenantId: <tenantId>
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: email-host-user
          objectType: secret
        - |
          objectName: email-host-password
          objectType: secret
        - |
          objectName: secret-key
          objectType: secret
  secretObjects:
    - secretName: backend-secret
      type: Opaque
      labels:
        plug: backend-secret
      data:
        - objectName: db-password
          key:  DB_PASSWORD
        - objectName: email-host-user
          key:  EMAIL_HOST_USER
        - objectName: email-host-password
          key:  EMAIL_HOST_PASSWORD
        - objectName: secret-key
          key:  SECRET_KEY