apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: plug-namespace
spec:
  selector:
    plug: backend-pods
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP