apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: plug-namespace
spec:
  selector:
    plug: frontend-pods
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort