apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: plug-namespace
spec:
  selector:
    plug-admin: pgadmin-pods
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 80
  type: NodePort