apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config-map
  namespace: plug-namespace
  labels:
    plug: backend-config-map
data:
  DB_HOST: "db-service:5432"
  ALLOWED_HOSTS: "*"
  DEBUG: '1'
  USE_CACHE: '0'
  CACHE_ENDPOINT: 'no'
  CACHE_PASSWORD: 'no'