apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: django-rules
  namespace: monitoring
  labels:
    release: prometheus-grafana
spec:
  groups:
    - name: django.rules
      rules:
        - alert: APILatencySpike
          expr: |
            histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket[5m])) by (le, pod)) > 0.8
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "API latency in pod {{ $labels.pod }} increased"
            description: "The 95th percentile API response time in pod {{ $labels.pod }} exceeded 800 miliseconds in the last 5 minutes."
        - alert: HighErrorRatePerEndpoint
          expr: |
            sum by (view, method) (
              rate(django_http_responses_total_by_status_view_method_total{status=~"^5.."}[5m])
            )
            /
            sum by (view, method) (
              rate(django_http_responses_total_by_status_view_method_total[5m])
            ) != 0
            > 0.05
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High percentage of HTTP 5xx errors for endpoint {{ $labels.view }} with method {{ $labels.method }} in API"
            description: "Endpoint {{ $labels.view }} with method {{ $labels.method }} in API generates more than 5% HTTP 5xx errors in the last 5 minutes."
        - alert: HighHttp5xxErrorRateBackend
          expr: |
            sum by (pod) (
              rate(
                django_http_responses_total_by_status_view_method_total{
                  status=~"^5..",
                  view!~"<unnamed view>|health_check:health_check_home|prometheus-django-metrics"
                }[5m]
              )
            )
            /
            sum by (pod) (
              rate(
                django_http_responses_total_by_status_view_method_total{
                  view!~"<unnamed view>|health_check:health_check_home|prometheus-django-metrics"
                }[5m]
              ) != 0
            )
            > 0.05
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High percentage of HTTP 5xx errors in API pod { $labels.pod }"
            description: "The percentage of HTTP 5xx errors in API pod { $labels.pod } exceeded 5% in the last 5 minutes."
