name: The Plug CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  #build-backend:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #    - name: SonarCloud Scan
  #      uses: sonarsource/sonarcloud-github-action@master
  #      env:
  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #    - name: Set up JDK 17
  #      uses: actions/setup-java@v3
  #      with:
  #          distribution: temurin
  #          java-version: 17
  #          cache: maven
  #    - name: Grant execute permission for mvn
  #      run: chmod +x mvn
  #    - name: Build with Maven
  #      run: mvn verify
  #    - name: Build and push Docker Image
  #      uses: mr-smithers-excellent/docker-build-push@v4
  #      with:
  #          image: user/repo
  #          registry: docker.io
  #          username: ${{ secrets.DOCKER_USERNAME }}
  #          password: ${{ secrets.DOCKER_PASSWORD }}

  #build-frontend:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #    - name: SonarCloud Scan
  #      uses: sonarsource/sonarcloud-github-action@master
  #      env:
  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #    - name: Set up NodeJS
  #      uses: actions/setup-node@v4
  #      with:
  #       node-version: 21
  #    - name: Grant execute permission for npm
  #      run: chmod +x npm
  #    - name: Install dependencies with npm
  #      run: npm install
  #    - name: Test with npm
  #      run: npm test
  #    - name: Build with npm
  #      run: npm run build
  #    - name: Build and push Docker Image
  #      uses: mr-smithers-excellent/docker-build-push@v4
  #      with:
  #        image: user/repo
  #        registry: docker.io
  #        username: ${{ secrets.DOCKER_USERNAME }}
  #        password: ${{ secrets.DOCKER_PASSWORD }}

  #docker-compose-down:
  #  needs: [ build-backend, build-frontend ]
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Shutdown application containers
  #      run: ssh user@host "docker compose -f docker-compose.yml down"

  #docker-compose-up:
  #  needs: [ docker-compose-down ]
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Login to docker
  #      run: ssh user@host "docker login"
  #    - name: Pull docker images
  #      run: ssh user@host "docker compose pull"
  #    - name: Run docker-compose.yml
  #      run: ssh user@host "docker compose -f docker-compose.yml up -d"