name: The Plug Svelte frontend CI

on:
  push:
    branches: [ main ]
    paths:
      - frontend/the_plug_frontend_svelte/**
  workflow_dispatch:

jobs:
  sonarcloud-scan-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-deploy-to-registry-frontend:
    needs: [ sonarcloud-scan-frontend ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
         node-version: 21
      - name: Install dependencies with npm
        run: npm install
      - name: Test with npm
        run: npm test
      - name: Build with npm
        run: npm run build
      - name: Build and push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: wallys02/the-plug-frontend
            tags: latest
            registry: docker.io
            dockerfile: frontend/the_plug_frontend_svelte/Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
  
