name: The Plug Svelte frontend CI/CD

on:
  push:
    branches: [ cicd ] # TODO change to main after debug
    paths:
      - frontend/the_plug_svelte_frontend/**
  pull_request:
    branches: [ cicd ] # TODO change to main after debug
    paths:
      - frontend/the_plug_svelte_frontend/**
  workflow_dispatch:

env:
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_HOST: ${{ secrets.DB_HOST }}
  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
  EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
  DEBUG: ${{ secrets.DEBUG }}
  USE_CACHE: 0
  CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
  CACHE_PASSWORD: ${{ secrets.CACHE_PASSWORD }}
  DOCKER_REGISTRY: 'docker.io/wallys'
  FRONTEND_IMAGE: 'wallys02/the-plug-frontend'
  AWS_REGION: 'eu-north-1'

jobs:
  sonarqube-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Linting + SAST scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: frontend/the_plug_svelte_frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}


  build-and-test-frontend:
    runs-on: ubuntu-latest
    needs: [ sonarqube-frontend ]
    if: github.ref == 'refs/heads/cicd' # TODO change to main after debug
    defaults:
      run:
        working-directory: frontend/the_plug_svelte_frontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: frontend/the_plug_svelte_frontend/package-lock.json

      - name: Install npm dependencies
        run: npm ci

      - name: Run npm tests
        run: npm run test

      - name: Build npm
        run: npm run build

      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/the_plug_svelte_frontend/dist/
          retention-days: 1


  backend-dependencies:
    runs-on: ubuntu-latest
    needs: [ sonarqube-frontend ]
    if: github.ref == 'refs/heads/cicd' # TODO change to main after debug
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: backend/the_plug_backend_django/requirements.txt

      - name: Install pip dependencies
        working-directory: backend/the_plug_backend_django
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


  e2e-tests:
    runs-on: ubuntu-latest
    needs: [ build-and-test-frontend, backend-dependencies ]
    if: github.ref == 'refs/heads/cicd' # TODO change to main after debug
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: backend/the_plug_backend_django/requirements.txt

      - name: Install cached pip dependencies
        working-directory: backend/the_plug_backend_django
        run: pip install -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: frontend/the_plug_svelte_frontend/package-lock.json

      - name: Install cached npm dependencies
        working-directory: frontend/the_plug_svelte_frontend
        run: npm ci

      - name: Run Django makemigrations
        working-directory: backend/the_plug_backend_django
        run: python manage.py makemigrations api --settings=the_plug_backend_django.e2e_test_settings

      - name: Run Django migrations
        working-directory: backend/the_plug_backend_django
        run: python manage.py migrate --settings=the_plug_backend_django.e2e_test_settings

      - name: Run Django loaddata
        working-directory: backend/the_plug_backend_django
        run: python manage.py loaddata api/fixtures/herbs.json --settings=the_plug_backend_django.e2e_test_settings

      - name: Run Django backend
        working-directory: backend/the_plug_backend_django
        run: python manage.py runserver 0.0.0.0:8080 --settings=the_plug_backend_django.e2e_test_settings &

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          config-file: frontend/the_plug_svelte_frontend/cypress.config.ts
          browser: chrome
          wait-on: http://localhost:8080/api/herb/list/
          config: baseUrl=http://localhost:4200
          working-directory: frontend/the_plug_svelte_frontend
          start: npm run dev -- --port 4200


  performance-tests:
    runs-on: ubuntu-latest
    needs: [ build-and-test-frontend, backend-dependencies ]
    if: github.ref == 'refs/heads/cicd' # TODO change to main after debug
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: backend/the_plug_backend_django/requirements.txt

      - name: Install cached pip dependencies
        working-directory: backend/the_plug_backend_django
        run: pip install -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: frontend/the_plug_svelte_frontend/package-lock.json

      - name: Install cached npm dependencies
        working-directory: frontend/the_plug_svelte_frontend
        run: npm ci

      - name: Run Django makemigrations
        working-directory: backend/the_plug_backend_django
        run: python manage.py makemigrations api --settings=the_plug_backend_django.e2e_test_settings

      - name: Run Django migrations
        working-directory: backend/the_plug_backend_django
        run: python manage.py migrate --settings=the_plug_backend_django.e2e_test_settings

      - name: Run Django loaddata
        working-directory: backend/the_plug_backend_django
        run: python manage.py loaddata api/fixtures/herbs.json --settings=the_plug_backend_django.e2e_test_settings

      - name: Run Django backend
        working-directory: backend/the_plug_backend_django
        run: python manage.py runserver 0.0.0.0:8080 --settings=the_plug_backend_django.e2e_test_settings &

      - name: Run Svelte frontend
        working-directory: frontend/the_plug_svelte_frontend
        run: npm run dev -- --port 4200 &

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: http://localhost:4200
          temporaryPublicStorage: true
          uploadArtifacts: true


  dast-tests:
    runs-on: ubuntu-latest
    needs: [ build-and-test-frontend, backend-dependencies ]
    if: github.ref == 'refs/heads/cicd' # TODO change to main after debug
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: backend/the_plug_backend_django/requirements.txt

      - name: Install cached pip dependencies
        working-directory: backend/the_plug_backend_django
        run: pip install -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: frontend/the_plug_svelte_frontend/package-lock.json

      - name: Install cached npm dependencies
        working-directory: frontend/the_plug_svelte_frontend
        run: npm ci

      - name: Run Django makemigrations
        working-directory: backend/the_plug_backend_django
        run: python manage.py makemigrations api --settings=the_plug_backend_django.e2e_test_settings

      - name: Run Django migrations
        working-directory: backend/the_plug_backend_django
        run: python manage.py migrate --settings=the_plug_backend_django.e2e_test_settings

      - name: Run Django loaddata
        working-directory: backend/the_plug_backend_django
        run: python manage.py loaddata api/fixtures/herbs.json --settings=the_plug_backend_django.e2e_test_settings

      - name: Run Django backend
        working-directory: backend/the_plug_backend_django
        run: python manage.py runserver 0.0.0.0:8080 --settings=the_plug_backend_django.e2e_test_settings &

      - name: Run Svelte frontend
        working-directory: frontend/the_plug_svelte_frontend
        run: npm run dev -- --port 4200 &

      - name: OWASP ZAP scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: http://localhost:4200
          allow_issue_writing: false



  docker-build-and-push-frontend:
    runs-on: ubuntu-latest
    needs: [ e2e-tests, performance-tests, dast-tests ]
    if: github.ref == 'refs/heads/cicd' && (success() || failure()) # TODO change to main after debug
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./frontend/the_plug_svelte_frontend/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max


  deploy-s3-frontend:
    runs-on: ubuntu-latest
    needs: [ e2e-tests, performance-tests, dast-tests ]
    if: github.ref == 'refs/heads/main' && (success() || failure()) # TODO change to main after debug
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend/the_plug_svelte_frontend/dist/

      - name: Sync frontend with S3
        working-directory: frontend/the_plug_svelte_frontend
        run: aws s3 sync dist s3://${{ secrets.S3_BUCKET }} --delete